lexik_jwt_authentication:
    private_key_path: %env(resolve:JWT_SECRET_KEY)%
    public_key_path:  %env(resolve:JWT_PUBLIC_KEY)%
    pass_phrase:      %env(resolve:JWT_PASSPHRASE)%
    token_ttl:        %env(resolve:JWT_TOKEN_TTL)%